### ISSUE TITLE
getBlocks() starts at the -, - world border instead of 0, 0

### ISSUE THREAD

**Issue by Red-exe-Engineer** [Bigjango13/MCPI-Addons#2]

**Comment by Bigjango13** [comment]
Does this happen with `getBlocks3D` too? `getBlocks` is just a wrapper that flattens the list.

**Comment by Bigjango13** [comment]
I cannot reproduce this, it can't be a wrong version problem because `getBlocks` was added in the newest version. Could you send the steps to reproduce?

**Comment by Bigjango13** [comment]
I have found and fixed it, the fix will be in v1.2.0. Thanks for reporting it.

**Comment by Bigjango13** [comment]
Fixed in 285dfb0.
