### ISSUE TITLE
`mc.override()` doesn't support data.

### ISSUE THREAD

**Issue by Red-exe-Engineer** [Bigjango13/MCPI-Addons#8]
I'm about to update it to handle `mc.block.Block` and noticed that it uses [sscanf(args.c_str(), "%i,%i", &before, &after)](https://github.com/Bigjango13/MCPI-Addons/blob/125b23cebf774ec81a44cd22769f3e5a203330ba/src/api.cpp#L160C27-L160C27), can this be changed to accept meta data values?

**Comment by Bigjango13** [comment]
Sadly not, that would require a *lot* more work than just swapping out a few pointers.
